#!/usr/bin/env node
/**
 * SpotiDuck UI bundler.
 *
 * Produces `dist/spotiduck-ui.js`: ONE JavaScript string that the Android app
 * can hand to `WebView.evaluateJavascript()` — CSS included. That mirrors how
 * the previous implementation shipped its injected script (a single string in
 * `C1356q3.onPageFinished`) while keeping the source readable here.
 *
 *   node tools/build.mjs [--watch]
 *
 * Output shape:
 *   (function () { "use strict";
 *     var SD_CSS_SOURCES = "<all css>";
 *     <runtime source, unmodified>
 *   })();
 */
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { watch } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src", "inject");
const OUT = join(root, "dist", "spotiduck-ui.js");

const pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8").catch(() => "{}"));
const VERSION = pkg.version || "0.0.0";

/** Strip comments + collapse whitespace. Keeps the bundle small without
 *  mangling strings (the runtime builds HTML strings — never minify those). */
function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .replace(/\s+/g, " ")
    .trim();
}

async function build() {
  const files = (await readdir(SRC)).filter((f) => f.endsWith(".css")).sort();
  const cssParts = [];
  for (const f of files) {
    const css = await readFile(join(SRC, f), "utf8");
    cssParts.push(`/* ${f} */\n${minifyCss(css)}`);
  }
  const css = cssParts.join("\n");

  const runtime = await readFile(join(SRC, "spotiduck-ui.js"), "utf8");

  const banner = `/*! SpotiDuck mobile UI v${VERSION} — generated by tools/build.mjs, do not edit.
    Inject with: webView.evaluateJavascript(bundle, null) on onPageFinished. */
`;
  /* The runtime is already an IIFE; we only need to define SD_CSS_SOURCES in
     an enclosing scope before it runs. No source rewriting (that is how
     bundling scripts usually break). */
  const bundle =
    banner +
    "(function () {\n" +
    '  "use strict";\n' +
    "  var SD_CSS_SOURCES = " +
    JSON.stringify(css) +
    ";\n" +
    runtime +
    "\n})();\n";

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, bundle, "utf8");
  const kb = (Buffer.byteLength(bundle) / 1024).toFixed(1);
  return { out: OUT, kb, files };
}

const result = await build();
console.log(`✔ dist/spotiduck-ui.js  (${result.kb} kB, ${result.files.length} css parts)`);
console.log(`  sources: ${result.files.join(", ")}`);

if (process.argv.includes("--watch")) {
  console.log("… watching src/inject");
  let t = 0;
  watch(SRC, () => {
    clearTimeout(t);
    t = setTimeout(() => build().then((r) => console.log(`↻ rebuilt (${r.kb} kB)`)), 120);
  });
}
